"""
Prompts module for the research agent.
Exports all prompt templates for easy importing.
"""
from .structured_outputs import (
    QUERY_GENERATION_SYSTEM_PROMPT,
    QUERY_GENERATION_USER_PROMPT_TEMPLATE,
    SUPERVISOR_SYSTEM_PROMPT_TEMPLATE,
    SUPERVISOR_FOLLOW_UP_SYSTEM_PROMPT_TEMPLATE,
    SUPERVISOR_USER_PROMPT_TEMPLATE,
    SUPERVISOR_FOLLOW_UP_CONTEXT_TEMPLATE,
)
from .report_prompts import (
    FINAL_REPORT_PROMPT_TEMPLATE,
    FINAL_REPORT_REFINEMENT_PROMPT_TEMPLATE,
)
from .research_prompts import (
    RESEARCH_SYNTHESIS_PROMPT_TEMPLATE,
)
from .thread_prompts import (
    THREAD_NAME_GENERATION_PROMPT_TEMPLATE,
)

__all__ = [
    "QUERY_GENERATION_SYSTEM_PROMPT",
    "QUERY_GENERATION_USER_PROMPT_TEMPLATE",
    "SUPERVISOR_SYSTEM_PROMPT_TEMPLATE",
    "SUPERVISOR_FOLLOW_UP_SYSTEM_PROMPT_TEMPLATE",
    "SUPERVISOR_USER_PROMPT_TEMPLATE",
    "SUPERVISOR_FOLLOW_UP_CONTEXT_TEMPLATE",
    "FINAL_REPORT_PROMPT_TEMPLATE",
    "FINAL_REPORT_REFINEMENT_PROMPT_TEMPLATE",
    "RESEARCH_SYNTHESIS_PROMPT_TEMPLATE",
    "THREAD_NAME_GENERATION_PROMPT_TEMPLATE",
]

