"""
Prompts module for the research agent.
Exports all prompt templates for easy importing.
"""
from .researcher import (
    QUERY_GENERATION_SYSTEM_PROMPT,
    QUERY_GENERATION_USER_PROMPT_TEMPLATE,
    RESEARCH_SYNTHESIS_PROMPT_TEMPLATE,
)
from .supervisor import (
    SUPERVISOR_SYSTEM_PROMPT_TEMPLATE,
    SUPERVISOR_FOLLOW_UP_SYSTEM_PROMPT_TEMPLATE,
    SUPERVISOR_USER_PROMPT_TEMPLATE,
    SUPERVISOR_FOLLOW_UP_CONTEXT_TEMPLATE,
)
from .response_generator import (
    FINAL_RESPONSE_PROMPT_TEMPLATE,
    FINAL_RESPONSE_REFINEMENT_PROMPT_TEMPLATE,
    DIRECT_ANSWER_PROMPT_TEMPLATE,
    FORMAT_INSTRUCTIONS_CONCISE,
    FORMAT_INSTRUCTIONS_REPORT,
)
from .thread_prompts import (
    THREAD_NAME_GENERATION_PROMPT_TEMPLATE,
)

__all__ = [
    "QUERY_GENERATION_SYSTEM_PROMPT",
    "QUERY_GENERATION_USER_PROMPT_TEMPLATE",
    "RESEARCH_SYNTHESIS_PROMPT_TEMPLATE",
    "SUPERVISOR_SYSTEM_PROMPT_TEMPLATE",
    "SUPERVISOR_FOLLOW_UP_SYSTEM_PROMPT_TEMPLATE",
    "SUPERVISOR_USER_PROMPT_TEMPLATE",
    "SUPERVISOR_FOLLOW_UP_CONTEXT_TEMPLATE",
    "FINAL_RESPONSE_PROMPT_TEMPLATE",
    "FINAL_RESPONSE_REFINEMENT_PROMPT_TEMPLATE",
    "DIRECT_ANSWER_PROMPT_TEMPLATE",
    "FORMAT_INSTRUCTIONS_CONCISE",
    "FORMAT_INSTRUCTIONS_REPORT",
    "THREAD_NAME_GENERATION_PROMPT_TEMPLATE",
]
