"""
Prompts module for the research agent.
Exports all prompt templates for easy importing.
"""
from .structured_outputs import (
    QUERY_GENERATION_SYSTEM_PROMPT,
    QUERY_GENERATION_USER_PROMPT_TEMPLATE,
    SUPERVISOR_SYSTEM_PROMPT_TEMPLATE,
    SUPERVISOR_FOLLOW_UP_SYSTEM_PROMPT_TEMPLATE,
    SUPERVISOR_USER_PROMPT_TEMPLATE,
    SUPERVISOR_FOLLOW_UP_CONTEXT_TEMPLATE,
)

__all__ = [
    "QUERY_GENERATION_SYSTEM_PROMPT",
    "QUERY_GENERATION_USER_PROMPT_TEMPLATE",
    "SUPERVISOR_SYSTEM_PROMPT_TEMPLATE",
    "SUPERVISOR_FOLLOW_UP_SYSTEM_PROMPT_TEMPLATE",
    "SUPERVISOR_USER_PROMPT_TEMPLATE",
    "SUPERVISOR_FOLLOW_UP_CONTEXT_TEMPLATE",
]

